# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_flopsearch_wrappers", use_symbols = TRUE, package_name = "flopsearch")

#' @usage NULL
#' @useDynLib flopsearch, .registration = TRUE
NULL

#' Run the FLOP causal discovery algorithm.
#'
#' For the given data and parameters, the FLOP algorithm is run and returns the learned graph as an adjacency matrix.
#'
#' @param data A data matrix with rows corresponding to observations and columns to variables/nodes.
#' @param lambdaBic The penalty parameter of the BIC, a typical value for structure learning is 2.0.
#' @param restarts Optional parameter specifying the number of ILS restarts. Either restarts or timeout (below) need to be specified.
#' @param timeout Optional parameter specifying a timeout after which the search returns. At least one local search is run up to a local optimum. Either restarts or timeout need to be specified.
#' @param outputDag Optional parameter to output a DAG instead of a CPDAG. Default value is FALSE.
#' @return A matrix encoding a CPDAG or DAG. The entry in row i and column j is 1 in case of a directed edge from i to j and 2 in case of an undirected edge between those nodes (an additional 2 in row j and column i is omitted).
#' @examples
#' p <- 10
#' W <- matrix(0, nrow = p, ncol = p)
#' W[cbind(1:(p-1), 2:p)] <- 1
#' X <- matrix(rnorm(10000 * p), nrow = 10000, ncol = p) %*% solve(diag(p) - W)
#' X_std <- scale(X)
#' flop(X, 2.0, restarts=20)
#' @export
flop <- function(data, lambdaBic, restarts = NA, timeout = NA, outputDag = FALSE) .Call(wrap__flop, data, lambdaBic, restarts, timeout, outputDag)


# nolint end
